name: "Build Nickel"
on: pull_request
jobs:
  run-benchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     ref: master
      #     fetch-depth: 0
      - uses: jasonwilliams/criterion-compare-action@move_to_actions
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-nickel:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: x86_64-darwin


    runs-on: ${{ matrix.os }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Add `unstable` Nix channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing nixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    - uses: cachix/cachix-action@v8
      with:
        name: nickel

    - name: Build Nickel
      run: |
        nix build ./#packages.${{ matrix.system }}.build

    - name: Run Makam Spec
      run: |
        nix build ./#checks.${{ matrix.system }}.specs
